title: Matías Andrade Guzmán
show_downloads: false
theme: jekyll-theme-minimal
livereload: true
github: 
  url: https://github.com/mandrade2
description: Pagina personal.
sass:
    style: compressed
motivation: Hacer de la tecnologia una herramienta para mejorar la calidad de vida de las personas es lo que me motiva. La tecnologia para solucionar problemas y hacer mejor la sociedad en que vivimos. Vivimos en una época donde poco queda para la imaginación y problemas tenemos por montones.
google_analytics: UA-111755237-1